name = "myexample"
uuid = "01236765-0244-4185-8fd5-fe60a02a63cb"
authors = ["andré Calero Valdez"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
